[project]
name = "hack-99690795-spectra"
version = "0.0.1"
description = "Project for Hackathon"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.0,<1.0.0",
    "openai>=1.100.0,<3.0.0",
    "python-dotenv>=1.1.0,<2.0.0",
    "uvicorn[standard]>=0.35.0,<1.0.0",
]

[tool.uv]
package = false
